name: Optimize & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Setup & Install Tools jika belum ada
    - name: Ensure Minifiers & cwebp Installed
      run: |
        GREEN="\033[0;32m"
        YELLOW="\033[1;33m"
        NC="\033[0m" # No Color

        check_or_install() {
          TOOL_NAME=$1
          INSTALL_CMD=$2
          if command -v $TOOL_NAME >/dev/null 2>&1; then
            echo -e "${GREEN}✅ $TOOL_NAME sudah tersedia.${NC}"
          else
            echo -e "${YELLOW}📦 Menginstall $TOOL_NAME...${NC}"
            eval "$INSTALL_CMD"
          fi
        }

        # HTML Minifier
        check_or_install "html-minifier" "npm install -g html-minifier"

        # CleanCSS
        check_or_install "cleancss" "npm install -g clean-css-cli"

        # Terser
        check_or_install "terser" "npm install -g terser"

        # cwebp
        check_or_install "cwebp" "sudo apt-get update && sudo apt-get install -y webp"

    # 3. Minify HTML
    - name: Minify HTML files
      run: |
        echo "🔹 Minifying HTML..."
        find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;

    # 4. Minify CSS
    - name: Minify CSS files
      run: |
        echo "🔹 Minifying CSS..."
        find . -name "*.css" -exec cleancss -o {} {} \;

    # 5. Minify JS
    - name: Minify JS files
      run: |
        echo "🔹 Minifying JS..."
        find . -name "*.js" -exec terser --compress --mangle -o {} -- {} \;

    # 6. Convert JPG/PNG to WebP
    - name: Convert JPG/PNG to WebP
      run: |
        echo "🔹 Converting images to WebP..."
        find . -type f \( -iname "*.jpg" -o -iname "*.png" \) -print0 | while IFS= read -r -d '' img; do
          cwebp -q 80 "$img" -o "${img%.*}.webp" && rm "$img"
        done

    # 7. Commit hasil optimasi
    - name: Commit optimized files
      run: |
        echo "🔹 Committing changes..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Optimize assets (minify + WebP)" || echo "No changes to commit"
        git push

    # 8. Deploy ke GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: |
          .git/*
