name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install minifiers
      run: |
        npm install -g html-minifier terser clean-css-cli

    - name: Minify HTML files
      run: |
        find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;

    - name: Minify CSS files
      run: |
        find . -name "*.css" -exec cleancss -o {} {} \;

    - name: Minify JS files
      run: |
        find . -name "*.js" -exec terser --compress --mangle -o {} -- {} \;

    - name: Install WebP Tools
      run: sudo apt-get install -y webp

    - name: Install & Convert JPG/PNG to WebP (safe)
      run: |
        # Install WebP tools
        sudo apt-get update
        sudo apt-get install -y webp

        # Cek apakah cwebp terinstall
        if ! command -v cwebp >/dev/null 2>&1; then
          echo "❌ cwebp not installed!"
          exit 1
        fi
        echo "✅ cwebp installed, version: $(cwebp -version)"

        # Konversi JPG/PNG ke WebP dan hapus file asli
        find . -type f \( -iname "*.jpg" -o -iname "*.png" \) -print0 | while IFS= read -r -d '' img; do
          cwebp -q 80 "$img" -o "${img%.*}.webp" && rm "$img"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: |
          .git/*
