name: Optimize & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Minify HTML (jika html-minifier tersedia)
    - name: Minify HTML files
      run: |
        if command -v html-minifier >/dev/null 2>&1; then
          find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;
        else
          echo "⚠️ html-minifier tidak tersedia, skip minify HTML."
        fi

    # 3. Minify CSS (jika cleancss tersedia)
    - name: Minify CSS files
      run: |
        if command -v cleancss >/dev/null 2>&1; then
          find . -name "*.css" -exec cleancss -o {} {} \;
        else
          echo "⚠️ clean-css-cli tidak tersedia, skip minify CSS."
        fi

    # 4. Minify JS (jika terser tersedia)
    - name: Minify JS files
      run: |
        if command -v terser >/dev/null 2>&1; then
          find . -name "*.js" -exec terser --compress --mangle -o {} -- {} \;
        else
          echo "⚠️ terser tidak tersedia, skip minify JS."
        fi

    # 5. Convert JPG/PNG to WebP (jika cwebp tersedia)
    - name: Convert JPG/PNG to WebP
      run: |
        if command -v cwebp >/dev/null 2>&1; then
          find . -type f \( -iname "*.jpg" -o -iname "*.png" \) -print0 | while IFS= read -r -d '' img; do
            cwebp -q 80 "$img" -o "${img%.*}.webp" && rm "$img"
          done
        else
          echo "⚠️ cwebp tidak tersedia, skip konversi WebP."
        fi

    # 6. Commit hasil optimasi
    - name: Commit optimized files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Optimize assets (minify + WebP)" || echo "No changes to commit"
        git push

    # 7. Deploy ke GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: |
          .git/*
