name: Optimize & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout full history supaya bisa commit
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Setup Node.js (untuk minifier)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Install minifiers
    - name: Install minifiers
      run: |
        npm install -g html-minifier terser clean-css-cli

    # 4. Minify HTML
    - name: Minify HTML files
      run: |
        find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;

    # 5. Minify CSS
    - name: Minify CSS files
      run: |
        find . -name "*.css" -exec cleancss -o {} {} \;

    # 6. Minify JS
    - name: Minify JS files
      run: |
        find . -name "*.js" -exec terser --compress --mangle -o {} -- {} \;

    # 7. Install & Convert JPG/PNG to WebP (gabungan + cek)
    - name: Install & Convert JPG/PNG to WebP (safe)
      run: |
        sudo apt-get update
        sudo apt-get install -y webp
        if ! command -v cwebp >/dev/null 2>&1; then
          echo "❌ cwebp not installed!"
          exit 1
        fi
        echo "✅ cwebp installed, version: $(cwebp -version)"
        find . -type f \( -iname "*.jpg" -o -iname "*.png" \) -print0 | while IFS= read -r -d '' img; do
          cwebp -q 80 "$img" -o "${img%.*}.webp" && rm "$img"
        done

    # 8. Commit hasil optimasi ke main
    - name: Commit optimized files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Optimize assets (minify + WebP)" || echo "No changes to commit"
        git push

    # 9. Deploy ke GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: |
          .git/*
