name: Optimize & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Ensure required tools
      run: |
        for tool in html-minifier terser clean-css-cli; do
          command -v $tool >/dev/null 2>&1 || npm install -g $tool
        done
        command -v cwebp >/dev/null 2>&1 || {
          sudo apt-get update
          sudo apt-get install -y webp
        }

    - name: Load minify cache
      run: |
        [ -f ".minify_cache" ] || touch ".minify_cache"

    - name: Minify HTML files (skip unchanged)
      run: |
        CACHE_FILE=".minify_cache"
        find . -type f -name "*.html" -print0 | while IFS= read -r -d '' file; do
          if [ "$file" -nt "$CACHE_FILE" ]; then
            html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "$file" "$file"
            echo "✅ Minified $file"
          else
            echo "⏩ Skipped $file (no change)"
          fi
        done

    - name: Minify CSS files (skip unchanged)
      run: |
        CACHE_FILE=".minify_cache"
        find . -type f -name "*.css" -print0 | while IFS= read -r -d '' file; do
          if [ "$file" -nt "$CACHE_FILE" ]; then
            cleancss -o "$file" "$file"
            echo "✅ Minified $file"
          else
            echo "⏩ Skipped $file (no change)"
          fi
        done

    - name: Minify JS files (skip unchanged)
      run: |
        CACHE_FILE=".minify_cache"
        find . -type f -name "*.js" -print0 | while IFS= read -r -d '' file; do
          if [ "$file" -nt "$CACHE_FILE" ]; then
            terser --compress --mangle -o "$file" -- "$file"
            echo "✅ Minified $file"
          else
            echo "⏩ Skipped $file (no change)"
          fi
        done

    - name: Convert JPG/PNG to WebP (skip unchanged)
      run: |
        CACHE_FILE=".minify_cache"
        echo "cwebp version: $(cwebp -version)"
        find . -type f \( -iname "*.jpg" -o -iname "*.png" \) -print0 | while IFS= read -r -d '' img; do
          if [ "$img" -nt "$CACHE_FILE" ]; then
            cwebp -q 80 "$img" -o "${img%.*}.webp" && rm "$img"
            echo "✅ Converted $img"
          else
            echo "⏩ Skipped $img (no change)"
          fi
        done

    - name: Update cache timestamp
      run: |
        touch .minify_cache

    # Tambahan: pastikan repo Git ada dan remote benar
    - name: Setup Git for commit
      run: |
        if [ ! -d .git ]; then
          git init
          git remote add origin https://github.com/LokaLaku/lokalaku.git
          git fetch origin
          git checkout main || git checkout -b main
        fi
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit optimized files
      run: |
        git add .
        git commit -m "Optimize assets (minify + WebP)" || echo "No changes to commit"
        git push origin main

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: |
          .git/*
